---
title: "HW1"
author: "Essie"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r Libraries, include = FALSE}
library(tidyverse)
library(usethis)
library(table1)
library(ggplot2)
library(here)

```

```{r Open Dataset, include = FALSE}
df <- read.csv(here("DataRaw","iq_data.csv"))

df_copy <- df
```

```{r Fix error}
#PI indicated that the 999 value was an error, needs to be corrected to 99. 
df <- df %>%
  mutate(IQ = if_else(IQ == 999, 99, IQ))

#ChatGPT help here to remember the mutate format.

```

In this study, individual IQs were measured. Each person's home residence was also categorized as either "Far" or "Near" the local smelter. Below is a table summarizing the findings, grouped by smelter distance.
```{r Create Table, echo = FALSE}
table <- table1(~IQ | Smelter, data = df)

table


```

Below is a plot displaying IQ by distance from the smelter.
```{r Plot Results, echo = TRUE}
#plot IQ according to distance
plot <- ggplot(df, aes(x = Smelter, y = IQ)) + 
  geom_boxplot() +
  labs(title = "IQ by Smelter Distance",
       caption = "Average IQ by distance from the local smelter")

plot
```



The mean IQ was 
```{r Calculations, echo= FALSE}

#overall mean
overall_mean <- mean(df$IQ)
overall_mean
```

The IQ by group is shown below.
```{r Calculations, ec}
df %>%
  group_by(Smelter) %>%
  summarise(mean_IQ = mean(IQ, na.rm = TRUE))

#A little ChatGPT help here to remember the group_by. I didn't use R all summer! I'm rusty!

```

```{r}
file.rename(
  "Code/HW1_Code.docx",
  "Reports/HW1_Code.docx"
)
```